### ISSUE TITLE
Syntax erroor

### ISSUE THREAD

**Issue by okhatlen** [thomasloven/homeassistant-lovelace-gen#12]
Hi, not very experienced programmer, so hope you bare with me

When I try to run with python3 lovelace-gen.py
I got syntax error on line 45 return f'{path}&{str(timestamp)}' with the last apostrophe ' highligted

After som tries I changed to comma after return f on both line 45 and 47, the I got error regarding the ?, and changed that ? to & and it run. And i made a ui_lovelace.yaml containing only this: 
```
# This file is automatically generated by lovelace-gen.py`
# https://github.com/thomasloven/homeassistant-lovelace-gen
# Any changes made to it will be overwritten the next time the script is run.
null
...
```

what am I doing wrong?

**Comment by thomasloven** [comment]
Which version of python3 do you have?

`$ python3 --version`

**Comment by okhatlen** [comment]
I have Python 3.5.3, I try to find an update, didn't think about that, Sorry. will try and let you know

**Comment by thomasloven** [comment]
Well.. to be fair, I've said it should work with the python that runs Home Assistant, and that's 3.5.3 or later... perhaps I should remove the f-strings...

**Comment by thomasloven** [comment]
Fixed
