### ISSUE TITLE
Error when using popup cards.

### ISSUE THREAD

**Issue by jazzyisj** [thomasloven/homeassistant-lovelace-gen#14]
HA 89.2,  lovelace-gen commit  e5429f1

lovelace-gen is failing to put a newline after the last resource item and the popup cards declaration resulting in popup cards not functioning.  Nothing is written to lovelace-gen.log.

![image](https://user-images.githubusercontent.com/44064559/54845782-aa804980-4cb0-11e9-813b-9ec87cbcec13.png)

main.yaml

```
title: Home Assistant
resources: !include lovelace_resources.yaml
popup_cards: !include lovelace_popups.yaml
views:
  - !include lovelace_home.yaml
  - !include lovelace_alarm.yaml
  - !include lovelace_presence.yaml
  - !include lovelace_schedule.yaml
  - !include lovelace_climate.yaml
  - !include lovelace_lights.yaml
  - !include lovelace_ceiling_fans.yaml
  - !include lovelace_garage.yaml
  - !include lovelace_sensors.yaml
  - !include lovelace_media.yaml
  - !include lovelace_cameras.yaml
  - !include lovelace_sprinklers.yaml  
  - !include lovelace_weather.yaml
  - !include lovelace_system.yaml
  - !include lovelace_test.yaml
```

**Comment by thomasloven** [comment]
I'm guessing you are a windows user?
Windows is the only known operating system in the galaxy which doesn't end a file with a newline.

I'll see what I can do about it...

**Comment by jazzyisj** [comment]
Yes, I am.  But I use the Cloud 9 addon as my IDE.  I do have Unix line endings enabled.  But maybe windows still causes an issue?  I use Chrome for a browser if that helps.

Thanks for looking into it!

![image](https://user-images.githubusercontent.com/44064559/54856274-00b0b500-4cd0-11e9-8422-dd2944f088ea.png)

**Comment by jazzyisj** [comment]
Ah ha!  Adding a blank line to my lovelace_resources.yaml include file solved the issue.   Maybe your script could check for a newline at the end of any include files?  A note in the documentation would help in the meantime.

I will close the issue if you wish.  Again thanks for your help.
