### ISSUE TITLE
Error Code 1

### ISSUE THREAD

**Issue by jokerigno** [thomasloven/homeassistant-lovelace-gen#16]
Hi,

I use the python without issue but I wanted to go deeper using !include.

I tried many different solutions but I always receive this error:

> Error running command: `python /config/lovelace-gen.py > /config/lovelace-gen.log`, return code: 1
> NoneType: None

I looked in the config and error 1 is not defined. 

Can you please support me?

**Comment by thomasloven** [comment]
Try also adding `2>&1` to the end of the command to also get any system errors output to the log.

**Comment by jokerigno** [comment]
I'm running HA in docker so how can I do this?

**Comment by thomasloven** [comment]
The same way you added the `python /config/lovelace-gen.py > /config/lovelace-gen.log` command. Just add ` 2>&1` to the end of it...

**Comment by jokerigno** [comment]
OK now i can see errors in log. Thank you!
