### ISSUE TITLE
Running HA In docker, lovelave-gen shell_command does not work. (Error Code -11)

### ISSUE THREAD

**Issue by TheDevFreak** [thomasloven/homeassistant-lovelace-gen#17]
I have tried loglevel debug and `2>&1` as per #16 and the only info I have in the log is:

```
2019-07-24 15:00:30 ERROR (MainThread) [homeassistant.components.shell_command] Error running command: `python /config/lovelace-gen.py > /config/lovelace-gen.log`, return code: -11
NoneType: None
```

If I run `docker exec -it homeassistant_homeassistant_1 python /config/lovelace-gen.py` It works fine.

**Comment by thomasloven** [comment]
I just released `lovelace_gen`, which replaces `lovelace-gen`.
You'll never have this problem with that.

Check it out!
https://github.com/thomasloven/hass-lovelace_gen
