### ISSUE TITLE
unable to run lovelace-gen.py

### ISSUE THREAD

**Issue by Jmilesy** [thomasloven/homeassistant-lovelace-gen#8]
Hi - I have tried to run follow the instruction but with the following result.

I am sure I am missing a step:
I have created the folder and file as required:

_**Create a directory <homeassistant config dir>/lovelace and the file <homeassistant config dir>/lovelace/main.yaml**_

```
root@raspberry:/home/homeassistant/.homeassistant/lovelace# dir

main.yaml
```

_**Inside your homeassistant config directory, run the command:**_

_**./lovelace-gen.py**_

_**This will create the file ui_lovelace.yaml.**_

it then fails with the following:
```
root@raspberry:/home/homeassistant/.homeassistant# ./lovelace-gen.py
/usr/bin/env: ‘python3\r’: No such file or directory
root@raspberry:/home/homeassistant/.homeassistant# python3 --version
Python 3.5.3
root@raspberry:/home/homeassistant/.homeassistant#
```

any advice would be gratefully received

**Comment by thomasloven** [comment]
You seem to have gotten a stray windows line ending into the file somehow.
How did you download it?

**Comment by Jmilesy** [comment]
copied the raw code into a text utf-8 document i have created in the directory, made sure that it was utf8 when it was saved

**Comment by thomasloven** [comment]
Try right clicking the "Raw" button and selecting "Save Link As..." or similar instead.

**Comment by Jmilesy** [comment]
I am an idiot

I did not precede the file with python3;

`/homeassistant/.homeassistant# python3 ./lovelace-gen.py`

works fine
