### ISSUE TITLE
there is a error cannot run lovelace-gen.py

### ISSUE THREAD

**Issue by plutosherry** [thomasloven/homeassistant-lovelace-gen#9]
Traceback (most recent call last):
  File "./lovelace-gen.py", line 31, in <module>
    import yaml
ImportError: No module named 'yaml'

**Comment by thomasloven** [comment]
From Readme.md:
> Note: lovelace-gen requires some non-standard python packages to be installed, namely PyYAML, requests and Jinja2. Those are all required by home-assistant, so by running the script in the same environment as hass, you'll get them for free. Also, python3 is required.

How are you trying to run the script? How do you run Home Assistant?

**Comment by plutosherry** [comment]
OK i have been installed python3-yaml  python3-jinja2 python3-requests
then it's works!!! thanks alots!
